### PR TITLE
Separate format specifier to prevent php warning message

### PR DESCRIPTION
**Pull request by willowmagrini**
### Description
This pull request addresses the issue with format specifiers in some messages, which caused warnings and even fatal errors. The fix separates the format specifier to ensure proper argument handling in the printf function.

### Problem
- Warnings and fatal errors were encountered due to incorrect format specifier usage in the printf function.
- Screenshots of the warnings and errors are attached below.

### Solution
- Corrected the format specifier by ensuring each placeholder is properly formatted and all necessary arguments are provided.

### Before
image
image

### After
The issue is resolved with no warnings or errors after applying the fix.

### Testing
- Tested the changes locally and at a stanging env and verified that the theme update message displays correctly without any warnings or errors.

Please review the changes and merge them into the main branch.

### CODE REVIEW

**Comment by afragen** [comment]
Thanks for this bug report and PR. Unfortunately there seem to be changes to composer libraries that don't belong here. Perhaps you can make them to the appropriate GitHub repository. 

One of these is my repository and I can fix it, `wp-dependency-installer`. The other is from the Freemius WordPress SDK and must be made there. 

Also, if you could also replace `git-updater-pro` with `git-updater` in the PR that would be great. If not I can made those changes. 

Thanks.

**Comment by afragen** [comment]
Can you provide the URL for the theme you are using, I would like to see if I can reproduce these issues.

Also, I'm not sure that spaces are required before or after a `printf()` or `sprint()` variable. Can you site some reference?

**Comment by afragen** [comment]
I updated some relevant `printf()` in `class Branches`. Can you see if the latest `develop` branch fixes this issue for you?

**Comment by afragen** [comment]
I'm away from my keyboard for a while but I don't see how your theme even interacts with Git Updater. I'll take a closer look when I get back.

**Comment by willowmagrini** [comment]
> I'm away from my keyboard for a while but I don't see how your theme even interacts with Git Updater. I'll take a closer look when I get back.

The theme of my repo is not on the root folder. I've created a symbolic link of the style.css on the root folder and set up the theme in the "Additions" tab from the git-updater configuration checking the asset checkbox:
image
I'm using docker, PHP 8.2.13 , WordPress 6.5.4. Also tested on php 8.3.7 where it only throws an warning, not an error

**Comment by afragen** [comment]
I am using LocalWP and I am unable to reproduce this issue. I am using the same entry to the Additions tab as you are.

### Environment
- WordPress: 6.5.4
- PHP: 8.2.10
- Server: nginx/1.16.0
- Database: mysqli (Server: 8.0.16 / Client: mysqlnd 8.2.10)
- Browser: Safari 17.5
- OS: macOS
- Theme: hacklabr 1.0.29
- MU Plugins: None activated
- Plugins:
  * Git Updater 12.4.0.4
  * Test Reports 1.1.0

### Expected Results
1.  Works as expected.

### Actual Results
1.  Works as expected. Unable to reproduce.


### Supplement
screenshot_571

screenshot_570

screenshot_572

**Comment by willowmagrini** [comment]
Maybe it's only happening on docker PHP images.  You can test using the same repo, just run docker-compose up inside the repo folder, when you access localhost it will be an WordPress installation page

**Comment by afragen** [comment]
I'll see about checking that using the `wordpress-develop` environment.

**Comment by afragen** [comment]
## Reproduction Report
### Description
Tested in the `wordpress-develop` Docker environment.

### Environment
- WordPress: 6.7-alpha-58576-src
- PHP: 8.2.20
- Server: nginx/1.27.0
- Database: mysqli (Server: 8.0.37 / Client: mysqlnd 8.2.20)
- Browser: Safari 17.5
- OS: macOS
- Theme: Twenty Twenty-Four 1.1
- MU Plugins:
  * MU Loader 0.5.0
  * WP-CLI: Force Auto-Updates 1.0.0
- Plugins:
  * Git Updater 12.4.0
  * Test Reports 1.1.0
  * WP Debugging 2.11.24

### Actual Results
Unable to reproduce error condition


### Supplemental Artifacts
screenshot_575

screenshot_576

**Comment by afragen** [comment]
Closing as unable to reproduce.

**Pull request closed without merging**
