### PR TITLE
Polyfill for NodeList.forEach

### PR DESCRIPTION
**Pull request by sharevb**
Polyfill for NodeList.forEach browser that supports ES5 like older IE

### CODE REVIEW

**Comment by afragen** [comment]
I confess to not being proficient in javascript. Can you explain the purpose and function of this PR?

Thanks.

**Comment by sharevb** [comment]
Some old browsers like IE11 don't have an implementation of `forEach` on `NodeList` and thus there is an JS error at [js/ghu-install-vanilla.js#L81](https://github.com/afragen/git-updater/blob/5b70fddaa00b4acbd8a00c40804d13ea741d5223/js/ghu-install-vanilla.js#L81). These polyfills implements `forEach` and `closest` of `Element` (in `element = item.parentElement.closest(selector);` above) for browser that don't have already.

I admit that IE11 must no longer be used but I logged such a JS error.

**Comment by afragen** [comment]
There is a plan to drop support for IE11 within WordPress entirely. https://make.wordpress.org/core/2021/03/04/discussion-dropping-support-for-ie11/

**Comment by afragen** [comment]
Is there a way to add this polyfill as a separate file?

**Comment by sharevb** [comment]
> There is a plan to drop support for IE11 within WordPress entirely. https://make.wordpress.org/core/2021/03/04/discussion-dropping-support-for-ie11/

Yes, I agree totally that IE11 should not be used anymore

> Is there a way to add this polyfill as a separate file?

May be but in fact, those polyfill "fills gaps" only if there is not an implementation of the given method and do nothing on other browser. So I don't think it is necessary to add one more JS for this.

**Comment by afragen** [comment]
@sharevb I've made a very large change to the `develop` branch. Much of it revolving around a rebrand. As such the file name for the JS file has changed. Can you pull the latest develop branch and adjust your PR?

If it's too much trouble, let me know and I'll pull it in.

**Comment by sharevb** [comment]
> @sharevb I've made a very large change to the `develop` branch. Much of it revolving around a rebrand. As such the file name for the JS file has changed. Can you pull the latest develop branch and adjust your PR?
> 
> If it's too much trouble, let me know and I'll pull it in.

Yes, no problem, done in #942

**Pull request closed without merging**
